### ISSUE TITLE
Incorrect config property for network request in documentation

### ISSUE THREAD

**Issue by georges** [bugsnag/bugsnag-cocoa-performance#103]
### Describe the bug
The [Documentation
](https://docs.bugsnag.com/performance/ios/#instrumenting-network-requests)
describe the network configuration property as `autoInstrumentNetworkRequests` but the code declares it as `autoInstrumentNetwork`

### Environment
* BugSnag Cocoa Performance version: 0.1.5
* CocoaPods version: 0.1.5

**Comment by johnkiely1** [comment]
Thanks for raising, were looking into it.

**Comment by johnkiely1** [comment]
Hi @georges, we have now updated the code in [v0.2.0](https://github.com/bugsnag/bugsnag-cocoa-performance/releases/tag/v0.2.0) to match as this was the intended name. Thanks again for raising.
