### ISSUE TITLE
Crash in the SpanAttributesProvider.mm file

### ISSUE THREAD

**Issue by AniHovhannisyanAni** [bugsnag/bugsnag-cocoa-performance#149]
Crash file is attached
[Crash.docx](https://github.com/bugsnag/bugsnag-cocoa-performance/files/11566187/Crash.docx)

**Comment by luke-belton** [comment]
Hi @AniHovhannisyanAni - thanks for raising this with us. We're investigating and will keep this thread updated 👍

**Comment by johnkiely1** [comment]
Hi @AniHovhannisyanAni, just to let you know we have fixed this in [v0.5.0](https://github.com/bugsnag/bugsnag-cocoa-performance/releases/tag/v0.5.0). 
Thanks again for raising. Do let us know if you see any further issues.

**Comment by AniHovhannisyanAni** [comment]
Hi @johnkiely1 , thank you so much!
