### ISSUE TITLE
Support for visionOS

### ISSUE THREAD

**Issue by yulian948** [bugsnag/bugsnag-cocoa-performance#275]
## Describe the bug
Trying to add bugsnag-cocoa-performance library to my VisionOS app, but receive build errors (see screenshot).

<img width="970" alt="Screenshot 2024-06-20 at 4 33 38 PM" src="https://github.com/bugsnag/bugsnag-cocoa-performance/assets/5032192/8fdfff97-c11f-4218-b93d-3b9c1c1aa281">

Errors are caused by the CoreTelephony framework unavailability on VisionOS. It seems that simple conditional compilation (#if TARGET_OS_IOS) should fix the issues.

## Steps to reproduce
Create an app in SwiftUI that runs on VisionOS
Link bugsnag-cocoa-performance.
Try to build the app

## Environment
BugSnag Performance library version: 1.6.0
VisionOS version: 1.1
Simulator or physical device: Both
Xcode version: 15.3
Swift version (if applicable): N.A

**Comment by matthewjhowells** [comment]
Hi @yulian948 ,

`bugsnag-cocoa-performance` is currently only supported for iOS applications. We’ve raised some work to investigate supporting BugSnag performance in visionOS, and while I don’t have an ETA I can share for this, we will be sure to update this thread once we have any updates.

It’s worth noting that the BugSnag notifiers are open source, so in the meantime you could try forking the `bugsnag-cocoa-performance` repo and try the `#if TARGET_OS_IOS` change you have suggested. Although please note that we would not be able to provide any support if issues occur.

**Comment by yulian948** [comment]
Hi @matthewjhowells ,
Thanks for your response. I will not use `bugsnag-cocoa-performance` now then, but will add it to my app when it becomes officially available for VisionOS.

**Comment by clr182** [comment]
Hi @yulian948 

Thank you for your patience, I just wanted to provide a quick update on the state of visionOS support. While we do not officially support the visionOS, we have completed some work that would allow the cocoa performance SDK to successfully build and report in a very basic sense. This comes with the caveat that, as it is not officially supported, we have not conducted a proper suit of tests for the platform. 

If you do run into any issues while using the platform, please do feel free to raise a new ticket to discuss the issue!
