### ISSUE TITLE
Warning: no rule to process file PrivacyInfo.xcprivacy of type 'text.xml' for architecture 'arm64'

### ISSUE THREAD

**Issue by combinatorial** [bugsnag/bugsnag-cocoa-performance#301]
### Describe the bug
Xcode reports "no rule to process file '<redacted>/Pods/BugsnagPerformance/Sources/BugsnagPerformance/resources/PrivacyInfo.xcprivacy' of type 'text.xml' for architecture 'arm64' (in target 'BugsnagPerformance' from project 'Pods')"

### Steps to reproduce
1. Build app

### Environment
* BugSnag Performance library version: 1.7.0
* BugSnag Error Monitoring library version (if any): 6.30.1
* CocoaPods version: 1.15.2
* iOS/tvOS/macOS version(s): 17
* Simulator or physical device: n/a
* Xcode version: 15.4 (15F31d)
* Swift version (if applicable):

### Solution

I think the solution is to change the podspec here: 
`"source_files": "Sources/BugsnagPerformance/**/*"`

to be more specific like here: https://github.com/bugsnag/bugsnag-cocoa/blob/b29cdabec2f0d396a6a80ca1cfe7ee0bfdf04992/Bugsnag.podspec.json#L54

**Comment by clr182** [comment]
Hi @combinatorial 

Thank you for reaching out and raising this issue. 

This does seem like a valid point. I've gone ahead and added this to our backlog and we will be sure to provide and update when priorities allow.

**Comment by RobertoSmartBear** [comment]
Hi @combinatorial 👋🏻,

The issue you’ve reported was fixed and deployed in the v1.8.1 release of bugsnag-cocoa-performance: [Release v1.8.1 · bugsnag/bugsnag-cocoa-performance](https://github.com/bugsnag/bugsnag-cocoa-performance/releases/tag/v1.8.1) 

Thanks for letting us know about this and please feel free to reach out again if you notice any further issues after upgrading your BugSnag Performance SDK.

**Comment by combinatorial** [comment]
thanks, I can confirm that's fixed.
